Repository SEONGNAM-SELLDOK/CLONE-PROJECT, pull requests merged in 2020-12, with the labels that each got.

#26 구직자 페이지 적용
  build.gradle
  src/main/java/com/selldok/toy/config/FilterTokenInfo.java
  src/main/java/com/selldok/toy/config/ROLE.java
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/config/SelldokSecurityFailHandler.java
  src/main/java/com/selldok/toy/config/SelldokSecurityFilter.java
  src/main/java/com/selldok/toy/config/SelldokUserToken.java
  src/main/java/com/selldok/toy/config/SimpleGrantedAuthority.java
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/employee/controller/AuthController.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/controller/MainController.java
  src/main/java/com/selldok/toy/employee/dao/EmployeeRepository.java
  src/main/java/com/selldok/toy/employee/model/AuthCallBackBody.java
  src/main/java/com/selldok/toy/employee/model/AuthCallBackRequest.java
  src/main/java/com/selldok/toy/employee/model/FaceBookTokenResponse.java
  src/main/java/com/selldok/toy/employee/model/Picture.java
  src/main/java/com/selldok/toy/employee/model/PictureInfo.java
  src/main/java/com/selldok/toy/employee/service/AuthService.java
  src/main/java/com/selldok/toy/employee/service/EmployeeService.java
  src/main/resources/application.yml
  src/main/resources/static/css/basicinfo.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/main.css
  src/main/resources/static/index.html
  src/main/resources/templates/employee/basicinfo.html
  src/main/resources/templates/employee/employee.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/main/index.html
  src/test/http/auth.http
  src/test/http/employee.http
Labels: 기능구현 - 백엔드

#32 검수 미적용 오류 수정
  src/main/java/com/selldok/toy/company/controller/BoardController.java
  src/main/java/com/selldok/toy/company/controller/CompanyController.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryCustom.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryImpl.java
  src/main/java/com/selldok/toy/company/dao/CompanyRepositoryImpl.java
  src/main/java/com/selldok/toy/company/dao/CompanySearchCondition.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/company/model/BoardCreateRequest.java
  src/main/java/com/selldok/toy/company/model/BoardListResponse.java
  src/main/java/com/selldok/toy/company/model/BoardReadResponse.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/company/service/CompanyService.java
  src/main/resources/application.yml
  src/main/resources/templates/board/add.html
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/create.html
Labels: 버그수정

#33 Toy error fix
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
Labels: 버그수정

#34 import 오류로 인한 gradle 추가
  build.gradle
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/service/EmployeeService.java
  src/main/resources/application.yml
Labels: 버그수정

#41 페이지 이동 처리 수정
  src/main/resources/templates/board/list.html
  src/main/resources/templates/company/create.html
  src/main/resources/templates/company/read.html
  src/main/resources/templates/employee/employee.html
Labels: 리팩토링, 버그수정

#35 PR 올립니다. 검토 부탁드려요~
  README.md
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepository.java
  src/main/java/com/selldok/toy/employee/entity/ApplyHistory.java
  src/main/java/com/selldok/toy/employee/entity/Employee.java
  src/main/java/com/selldok/toy/employee/model/ApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/main/resources/application.yml
  src/test/http/appliedCompany.http
Labels: 기능구현 - 백엔드

#44 Applied status
  build.gradle
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepository.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryCustom.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryImpl.java
  src/main/java/com/selldok/toy/employee/dao/QApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/entity/ApplyHistory.java
  src/main/java/com/selldok/toy/employee/entity/Employee.java
  src/main/java/com/selldok/toy/employee/model/ApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/test/http/appliedCompany.http
Labels: 기능구현 - 백엔드

#42 엔티티 컨트롤러 유효성 검사, Temporal, 동적 쿼리 적용
  build.gradle
  src/main/java/com/selldok/toy/company/controller/ApiControllerAdvice.java
  src/main/java/com/selldok/toy/company/controller/BoardController.java
  src/main/java/com/selldok/toy/company/controller/CompanyController.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryImpl.java
  src/main/java/com/selldok/toy/company/dao/BoardSearchCondition.java
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/entity/City.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/company/entity/Country.java
  src/main/java/com/selldok/toy/company/exception/NotEnoughStockExceprion.java
  src/main/java/com/selldok/toy/company/model/BoardCreateRequest.java
  src/main/java/com/selldok/toy/company/model/BoardReadResponse.java
  src/main/java/com/selldok/toy/company/model/BoardUpdateRequest.java
  src/main/java/com/selldok/toy/company/model/CompanyCreateRequest.java
  src/main/java/com/selldok/toy/company/model/CompanyUpdateRequest.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/company/service/CompanyService.java
  src/main/resources/static/css/board.css
  src/main/resources/templates/board/list.html
  src/main/resources/templates/company/create.html
Labels: 기능구현 - 백엔드

#45 #43 이벤트 프론트 페이지 추가
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/event/controller/EventController.java
  src/main/java/com/selldok/toy/event/mapper/EventMapper.java
  src/main/java/com/selldok/toy/event/model/EventSearchRequest.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/main/resources/mybatis/mapper/EventMapper.xml
  src/main/resources/static/css/eventdetail.css
  src/main/resources/static/css/eventlistForjobseeker.css
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/create.html
  src/main/resources/templates/company/read.html
  src/main/resources/templates/employee/basicinfo.html
  src/main/resources/templates/employee/employee.html
  src/main/resources/templates/event/eventdetail.html
  src/main/resources/templates/event/eventedit.html
  src/main/resources/templates/event/eventlist.html
  src/main/resources/templates/event/eventlistForjobseeker.html
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 백엔드
