Repository SEONGNAM-SELLDOK/CLONE-PROJECT, pull requests merged in 2021-01, with the labels that each got.

#47 신규 채용 회사 TOP4, 탐색 링크 추가
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryCustom.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryImpl.java
  src/main/java/com/selldok/toy/company/model/NewHireListResponse.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/controller/MainController.java
  src/main/java/com/selldok/toy/event/controller/EventController.java
  src/main/java/com/selldok/toy/event/mapper/EventMapper.java
  src/main/java/com/selldok/toy/event/model/EventSearchRequest.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/main/resources/mybatis/mapper/EventMapper.xml
  src/main/resources/static/css/eventdetail.css
  src/main/resources/static/css/eventlistForjobseeker.css
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/create.html
  src/main/resources/templates/company/read.html
  src/main/resources/templates/employee/basicinfo.html
  src/main/resources/templates/employee/employee.html
  src/main/resources/templates/event/eventdetail.html
  src/main/resources/templates/event/eventedit.html
  src/main/resources/templates/event/eventlist.html
  src/main/resources/templates/event/eventlistForjobseeker.html
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 백엔드, 기능구현 - 프론트

#51 메인페이지 API 연동 추가
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/config/SelldokUserToken.java
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/controller/MainController.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriend.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriendResult.java
  src/main/java/com/selldok/toy/employee/service/AuthService.java
  src/main/java/com/selldok/toy/event/controller/EventController.java
  src/main/java/com/selldok/toy/event/dao/EventRepository.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/main/resources/mybatis/mapper/EmployeeMapper.xml
  src/main/resources/static/css/employee.css
  src/main/resources/static/css/main.css
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 백엔드, 기능구현 - 프론트

#49 이벤트 검색 페이지 수정
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/config/SelldokUserToken.java
  src/main/java/com/selldok/toy/config/WebSecurityConfig.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/controller/MainController.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriend.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriendResult.java
  src/main/java/com/selldok/toy/employee/service/AuthService.java
  src/main/java/com/selldok/toy/event/dao/EventRepository.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/main/resources/mybatis/mapper/EmployeeMapper.xml
  src/main/resources/static/css/employee.css
  src/main/resources/static/css/main.css
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 프론트

#56 spring restdocs, swagger 적용
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/selldok/toy/company/dao/BoardRepository.java
  src/main/java/com/selldok/toy/company/dao/CompanyRepository.java
  src/main/java/com/selldok/toy/company/model/CompanyCreateRequest.java
  src/main/java/com/selldok/toy/config/Swagger2Config.java
  src/main/resources/static/docs/api-guide.html
  src/test/java/com/selldok/toy/common/RestDocsConfiguration.java
  src/test/java/com/selldok/toy/company/CompanyControllerTests.java
Labels: 기능구현 - 프론트, 문서화

#58 bug fix
  src/main/java/com/selldok/toy/config/MvcConfiguration.java
  src/main/java/com/selldok/toy/config/Swagger2Config.java
Labels: 버그수정

#57 지원현황 관련 화면 작업 pr 올립니다.
  src/main/java/com/selldok/toy/config/SelldokAuthenticationProvider.java
  src/main/java/com/selldok/toy/config/SelldokUserToken.java
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepository.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryCustom.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryImpl.java
  src/main/java/com/selldok/toy/employee/entity/ApplyHistory.java
  src/main/java/com/selldok/toy/employee/model/ApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/main/resources/static/css/applications.css
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/applications.html
  src/main/resources/templates/employee/applications.html
  src/main/resources/templates/main/index.html
  src/test/http/appliedCompany.http
Labels: 기능구현 - 프론트

#61 금주의 추천 api 개발
  src/main/java/com/selldok/toy/company/controller/BoardController.java
  src/main/java/com/selldok/toy/company/dao/BoardRepository.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryCustom.java
  src/main/java/com/selldok/toy/company/dao/BoardRepositoryImpl.java
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/model/RecommendThisWeekResponse.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/employee/controller/MainController.java
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/create.html
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 백엔드, 기능구현 - 프론트

#64 이미지 업로드 기능 개선
  build.gradle
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/config/CelldokFileUtil.java
  src/main/java/com/selldok/toy/config/FileProperties.java
  src/main/java/com/selldok/toy/config/MvcConfiguration.java
  src/main/java/com/selldok/toy/event/controller/EventController.java
  src/main/java/com/selldok/toy/event/model/InsertEventRequest.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/main/resources/application.yml
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/read.html
  src/main/resources/templates/event/eventedit.html
  src/main/resources/templates/main/index.html
  src/test/java/com/selldok/toy/config/CelldokFileUtilTest.java
Labels: 기능구현 - 백엔드, 리팩토링

#73 #71 test coverage
  README.md
  build.gradle
  src/main/java/com/selldok/toy/event/model/EventSearchRequest.java
  src/main/java/com/selldok/toy/event/model/InsertEventRequest.java
  src/main/java/com/selldok/toy/event/model/UpdateEventRequest.java
  src/main/java/com/selldok/toy/event/service/EventService.java
  src/test/java/com/selldok/toy/event/service/EventServiceTest.java
Labels: 기능구현 - 백엔드

#69 ControllerAdvice를 이용한 exception handler 구현
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/main/java/com/selldok/toy/exception/ApiErrorMsg.java
  src/main/java/com/selldok/toy/exception/ApplyErrorCode.java
  src/main/java/com/selldok/toy/exception/CommonErrorCode.java
  src/main/java/com/selldok/toy/exception/RestApiException.java
  src/main/java/com/selldok/toy/exception/RestApiExceptionHandler.java
  src/test/http/appliedCompany.http
  test/karate-0.9.6/employee.feature
Labels: 기능구현 - 백엔드

#72 spring cacheable 적용, 탐색page 페이징 적용
  src/main/java/com/selldok/toy/ToyApplication.java
  src/main/java/com/selldok/toy/company/controller/BoardController.java
  src/main/java/com/selldok/toy/company/model/BoardCountPlusRequest.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/config/CacheConfiguration.java
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/create.html
  src/main/resources/templates/company/list.html
  src/main/resources/templates/employee/employee.html
  src/main/resources/templates/main/index.html
Labels: 기능구현 - 백엔드

#75 지원관련 화면에서 실제 동작하지 않는 시각적 요소들 삭제, 상단에 있는 기업의 '지원현황' 링크에 기업id제거
  .gitignore
  src/main/java/com/selldok/toy/company/controller/CompanyController.java
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepository.java
  src/main/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryImpl.java
  src/main/java/com/selldok/toy/employee/entity/ApplyHistory.java
  src/main/java/com/selldok/toy/employee/entity/Employee.java
  src/main/java/com/selldok/toy/employee/model/ApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/main/resources/application.yml
  src/main/resources/templates/board/read.html
  src/main/resources/templates/company/applications.html
  src/main/resources/templates/employee/applications.html
  src/main/resources/templates/main/index.html
  src/test/http/appliedCompany.http
  test/karate-0.9.6/apply.feature
  test/karate-0.9.6/karate-config.js
Labels: 기능개선, 리팩토링

#78 #76 테스트 케이스(employee,auth)
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/config/RedisConfig.java
  src/main/java/com/selldok/toy/config/SelldokUserToken.java
  src/main/java/com/selldok/toy/employee/controller/AuthController.java
  src/main/java/com/selldok/toy/employee/controller/EmployeeController.java
  src/main/java/com/selldok/toy/employee/entity/Employee.java
  src/main/java/com/selldok/toy/employee/model/EmployeeProfileResponse.java
  src/main/java/com/selldok/toy/employee/model/EmployeeResponse.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriend.java
  src/main/java/com/selldok/toy/employee/model/FaceBookFriendResult.java
  src/main/java/com/selldok/toy/employee/model/FaceBookTokenResponse.java
  src/main/java/com/selldok/toy/employee/model/InsertEmployeeRequest.java
  src/main/java/com/selldok/toy/employee/model/UpdateEmployeeRequest.java
  src/main/java/com/selldok/toy/employee/model/UpdateProfileRequest.java
  src/main/java/com/selldok/toy/employee/service/AuthService.java
  src/main/java/com/selldok/toy/employee/service/EmployeeService.java
  src/main/resources/application.yml
  src/main/resources/log4jdbc.log4j2.properties
  src/test/java/com/selldok/toy/employee/controller/EmployeeControllerTest.java
  src/test/java/com/selldok/toy/employee/service/AuthServiceTest.java
  src/test/java/com/selldok/toy/employee/service/EmployeeServiceTest.java
Labels: 기능구현 - 백엔드, 문서화

#77 기업,구직 CRUD 테스크 코드, restdocs
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/selldok/toy/company/controller/BoardController.java
  src/main/java/com/selldok/toy/company/controller/CompanyController.java
  src/main/java/com/selldok/toy/company/dao/CompanyRepositoryImpl.java
  src/main/java/com/selldok/toy/company/entity/Company.java
  src/main/java/com/selldok/toy/company/entity/Member.java
  src/main/java/com/selldok/toy/company/entity/MemberStatus.java
  src/main/java/com/selldok/toy/company/model/BoardCreateRequest.java
  src/main/java/com/selldok/toy/company/model/BoardListResponse.java
  src/main/java/com/selldok/toy/company/model/BoardUpdateRequest.java
  src/main/java/com/selldok/toy/company/model/CompanyCreateRequest.java
  src/main/java/com/selldok/toy/company/model/CompanyListResponse.java
  src/main/java/com/selldok/toy/company/model/CompanyUpdateRequest.java
  src/main/java/com/selldok/toy/company/service/BoardService.java
  src/main/java/com/selldok/toy/company/service/CompanyService.java
  src/main/resources/application.yml
  src/test/java/com/selldok/toy/company/CompanyControllerTests.java
  src/test/java/com/selldok/toy/company/service/BoardControllerTests.java
  src/test/java/com/selldok/toy/company/service/CompanyControllerTests.java
Labels: 리팩토링, 문서화

#79 지원현황 관련 유닛테스트 & restdoc 반영 pr 올립니다.
  build.gradle
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/selldok/toy/employee/controller/ApplyHistoryController.java
  src/main/java/com/selldok/toy/employee/dao/QApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/model/ApplyHistoryDto.java
  src/main/java/com/selldok/toy/employee/service/AppliedHistoryService.java
  src/main/resources/application.yml
  src/test/java/com/selldok/toy/employee/controller/ApplyHistoryControllerTests.java
  src/test/java/com/selldok/toy/employee/dao/ApplyHistoryRepositoryImplTest.java
  src/test/java/com/selldok/toy/employee/service/AppliedHistoryServiceTest.java
Labels: 버그수정

#80 테스트코드 (WdListService, SalaryService)
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/selldok/toy/company/entity/Board.java
  src/main/java/com/selldok/toy/company/service/WdlistService.java
  src/main/java/com/selldok/toy/salary/model/SalaryRequest.java
  src/test/java/com/selldok/toy/company/service/WdlistServiceTest.java
  src/test/java/com/selldok/toy/salary/controller/SalaryControllerTest.java
  src/test/java/com/selldok/toy/salary/service/SalaryServiceTest.java
Labels: 문서화
